version: "3.2"
services:
  app:
    build:
      context: ./project
    image: zapp
    container_name: zapp
    restart: always
    command: >
      sh -c "python3 manage.py wait_for_db &&
            python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    container_name: zdb
    volumes:
      - ./db/:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - "5432"
