# Generated by Django 4.0.4 on 2022-06-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
